# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: BIHSAM - Arı Ürünleri
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  BIHSAM bal arı ürünleri, Samsum, Türkiye.
copyright: 'Copyright &copy; 2020 BIHSAM. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/bih.sam
  - title: instagram
    url: https://instagram.com/bihsambal
